services:
  rabbitmq:
    image: rabbitmq-managed-delayedexchange-alpine:v2
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq_definitions.json:/etc/rabbitmq/rabbitmq_definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
